
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Gramaticas.web;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int REALIZAR_SOLICITUD = 3;
  public static final int FIN_SOLICITUD = 4;
  public static final int ID_TRIVIA = 28;
  public static final int POR = 14;
  public static final int XSON_VERSION = 2;
  public static final int NOMBRE = 31;
  public static final int ELIMINAR_TRIVIA = 23;
  public static final int CHECKBOX = 38;
  public static final int DOS_PUNTOS = 10;
  public static final int MODIFICAR_USUARIO = 19;
  public static final int NOT = 17;
  public static final int AND = 15;
  public static final int USUARIO = 29;
  public static final int MODIFICAR_TRIVIA = 24;
  public static final int OR = 16;
  public static final int CORCHETE_CIERRA = 8;
  public static final int SELECCIONAR = 11;
  public static final int USUARIO_NUEVO = 18;
  public static final int FICHERO = 40;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 9;
  public static final int ELIMINAR_USUARIO = 20;
  public static final int NUMBER = 44;
  public static final int FECHA_MODIFICACION = 35;
  public static final int PASSWORD = 30;
  public static final int LLAVE_ABRE = 5;
  public static final int FECHA_CREACION = 34;
  public static final int TEMA = 33;
  public static final int CORCHETE_ABRE = 7;
  public static final int TIEMPO_PREGUNTA = 32;
  public static final int REPORTE = 12;
  public static final int RADIO = 39;
  public static final int OPERADOR = 45;
  public static final int MODIFICAR_COMPONENTE = 27;
  public static final int ELIMINAR_COMPONENTE = 26;
  public static final int COMBO = 41;
  public static final int AGREGAR_COMPONENTE = 25;
  public static final int STRING = 43;
  public static final int NUEVA_TRIVIA = 22;
  public static final int LLAVE_CIERRA = 6;
  public static final int AREA_TEXTO = 37;
  public static final int FILTRAR = 13;
  public static final int CAMPO_TEXTO = 36;
  public static final int LOGIN_USUARIO = 21;
  public static final int IDENTIFIER = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "XSON_VERSION",
  "REALIZAR_SOLICITUD",
  "FIN_SOLICITUD",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "COMA",
  "DOS_PUNTOS",
  "SELECCIONAR",
  "REPORTE",
  "FILTRAR",
  "POR",
  "AND",
  "OR",
  "NOT",
  "USUARIO_NUEVO",
  "MODIFICAR_USUARIO",
  "ELIMINAR_USUARIO",
  "LOGIN_USUARIO",
  "NUEVA_TRIVIA",
  "ELIMINAR_TRIVIA",
  "MODIFICAR_TRIVIA",
  "AGREGAR_COMPONENTE",
  "ELIMINAR_COMPONENTE",
  "MODIFICAR_COMPONENTE",
  "ID_TRIVIA",
  "USUARIO",
  "PASSWORD",
  "NOMBRE",
  "TIEMPO_PREGUNTA",
  "TEMA",
  "FECHA_CREACION",
  "FECHA_MODIFICACION",
  "CAMPO_TEXTO",
  "AREA_TEXTO",
  "CHECKBOX",
  "RADIO",
  "FICHERO",
  "COMBO",
  "IDENTIFIER",
  "STRING",
  "NUMBER",
  "OPERADOR"
  };
}

