
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Gramaticas.user;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVE_ABRE = 5;
  public static final int LLAVE_CIERRA = 6;
  public static final int CORCHETE_CIERRA = 8;
  public static final int FIN_SOLICITUD = 4;
  public static final int CORCHETE_ABRE = 7;
  public static final int IDENTIFIER = 18;
  public static final int ELIMINAR_USUARIO = 13;
  public static final int DOS_PUNTOS = 10;
  public static final int STRING = 19;
  public static final int USUARIO_NUEVO = 11;
  public static final int COMA = 9;
  public static final int NUMBER = 20;
  public static final int NOMBRE = 17;
  public static final int EOF = 0;
  public static final int PASSWORD = 16;
  public static final int error = 1;
  public static final int USUARIO = 15;
  public static final int LOGIN_USUARIO = 14;
  public static final int MODIFICAR_USUARIO = 12;
  public static final int XSON_VERSION = 2;
  public static final int REALIZAR_SOLICITUD = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "XSON_VERSION",
  "REALIZAR_SOLICITUD",
  "FIN_SOLICITUD",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "COMA",
  "DOS_PUNTOS",
  "USUARIO_NUEVO",
  "MODIFICAR_USUARIO",
  "ELIMINAR_USUARIO",
  "LOGIN_USUARIO",
  "USUARIO",
  "PASSWORD",
  "NOMBRE",
  "IDENTIFIER",
  "STRING",
  "NUMBER"
  };
}

